name: "varpipe_interpretation"
description: Custom module for determining drug resistance
keywords:
  - drug resistance
  - interpretation
  - tuberculosis
  - structural variants
  - target region coverage
tools:
  - "interpret":
      description: "Python script assessing sample drug resistance (DR)"
      homepage: "https://github.com/cdcent/oamd-bio-ph-core/modules/ph-core/varpipe/varpipe_interpretation/templates"
      identifier: ""
input:
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1', single_end:false ]`
    - summary:
        type: file
        description: Text file containing summary reports
        pattern: "*_summary.txt"
    - structuralVariants:
        type: file
        description: Text file containing reported structural variants
        pattern: "*_structural_variants.txt"
    - drLociAnnotation:
        type: file
        description: File containing drug resistance annotation
        pattern: "*_DR_loci_annotation.txt"
    - targetRegionCoverage:
        type: file
        description: File containing target region coverage information
        pattern: "*_target_region_coverage.txt"
  - - reported:
        type: file
        description: File containing reported variants
output:
  - summary:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "*_summary.txt":
          type: file
          description: |
            Summary report
          pattern: "*_summary.txt"
  - interpretation:
      - meta:
          type: file
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1', single_end:false ]`
      - "*_interpretation.txt":
          type: map
          description: |
            Interpretation report
          pattern: "*_interpretation.txt"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@ztb2"
  - "@lekalle"
  - "@craulers"
  - "@supark87"
  - "@smagala"
  - "@tstark-cdc"
maintainers:
  - "@ztb2"
  - "@lekalle"
  - "@supark87"
  - "@smagala"
  - "@tstark-cdc"
